### ISSUE TITLE
lack of fonts

### ISSUE THREAD

**Issue by guazontsubasa** [jannishajda/doc2pdf#1]
It doesn't have my fonts (MS Arial). The pdf file is all filled with squares for lacking of fonts.
In case you care about it. 
Thanks though, anyway

**Comment by JannisHajda** [comment]
Hey, thanks for your feedback! Although it took a while, I finally managed to find some time and added the option to add your own custom fonts :) Feel free, to check out the newest version - there are also some visual improvements
